[package]
name = "bevy_b3d"
version = "0.1.0"
edition = "2021"
description = "Bevy Engine B3D loading"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy
bevy = { version = "0.10.1", default-features = false }

# other
b3d = "0.1.5"
thiserror = "1.0.40"
anyhow = "1.0.68"
