[package]
name = "scpcb_redux"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]
resolver = "2"

[dependencies]
bevy_b3d = { path = "crates/bevy_b3d" }
bevy_rmesh = { path = "crates/bevy_rmesh" }
# bevy_xfile = { path = "crates/bevy_xfile" }
bevy_rapier3d = "0.21.0"
bevy-scene-hook = "6.0.0"
bevy-inspector-egui = "0.18.3"

[dependencies.bevy]
version = "0.10.1"
features = ["jpeg", "wayland"]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

